CREATE SCHEMA IF NOT EXISTS Booker;
USE Booker;

CREATE TABLE IF NOT EXISTS User (
	UserID VARCHAR(36) NOT NULL,
    Name VARCHAR(150) NOT NULL,
    Email VARCHAR(150) NOT NULL UNIQUE,
    Password VARCHAR(150) NOT NULL,
    BusinessOwner SMALLINT NOT NULL,
    PRIMARY KEY (UserID)
);

CREATE TABLE IF NOT EXISTS BusinessOwner (
    UserID VARCHAR(36) NOT NULL,
    BusinessName VARCHAR(150),
    BusinessType VARCHAR (150),
    Phone VARCHAR(150),
    Website VARCHAR(150), 
    FOREIGN KEY (UserID) REFERENCES User(UserID)   
);