CREATE SCHEMA IF NOT EXISTS Booker;
USE Booker;

CREATE TABLE IF NOT EXISTS User (
	UserID INT AUTO_INCREMENT NOT NULL,
    Email VARCHAR(150) NOT NULL,
	Username VARCHAR(150) NOT NULL,
    Password VARCHAR(150) NOT NULL,
    Name VARCHAR(150) NOT NULL,
    BusinessOwner SMALLINT NOT NULL,
    PRIMARY KEY (UserID)
);

SELECT * FROM User;